In [1]:
%cd "F:\Google Drive\JupyterNotebooks\PMega\Section 11 - Webmaps"
import os
os.listdir()

F:\Google Drive\JupyterNotebooks\PMega\Section 11 - Webmaps

['.~$Volcsmap.html.insyncdl',
 'Aus Volc.txt',
 'Aus Volc.xlsx',
 'aus volcs.xlsx',
 'code.py',
 'coordinates.json',
 'debug.txt',
 'debug_pop.txt',
 'desktop.ini',
 'GeoMap Project Polished.ipynb',
 'GeoMap Project.ipynb',
 'GVP_Volcano_List.xls',
 'GVP_Volcano_List.xlsx',
 'MyMap.html',
 'myvolcsmap.html',
 'out.txt',
 'popmap.html',
 'Popmap.ipynb',
 'subVolcs.html',
 'Testvolcsmap.html',
 'Untitled0.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Volcanoes_USA.csv',
 'Volcanoes_USA.txt',
 'VolcanoMap.html',
 'Volcsmap.html',
 'VolcsTestMap.html',
 'world.json',
 '~$Aus Volc.xlsx']

In [47]:
import pandas as pd
import folium as f

data = pd.read_excel("Aus Volc.xlsx")

In [39]:
aus_map = f.Map(tiles="Mapbox Bright")

In [48]:
data.head(5)

,Name,Elevation,DMS,DMS.1,Lat,Lon,Last Eruption
0,Atherton Volcano,—,17°30S 144°30E,17.5°S 144.5°E,144.5,-17.5,"Less than 100,000 years ago[1]"
1,Lake Barrine,730,17°12S 145°24E,17.2°S 145.4°E,145.4,-17.2,">17,000 years ago[1]"
2,Bauhinia Volcano,—,24°48S 149°30E,24.8°S 149.5°E,149.5,-24.8,23–25 million years ago
3,Brisbane Volcano,—,27°42S 152°36E,27.7°S 152.6°E,152.6,-27.7,16–62 million years ago
4,Cookie Mountains,—,50°54S 151°48E,50.9°S 151.8°E,151.8,-50.9,23 million years ago

In [50]:
aus_volcs = f.FeatureGroup(name="Aus Volcs")

lon = data["Lon"]
lat = data["Lat"]
name = data["Name"]

for la, lo, na in zip(lat,lon,name):
    aus_volcs.add_child(f.Marker(location=[lat,lon],popup=na))

TypeError: cannot convert the series to <class 'float'>

In [43]:
for i in lon:
    print(type(i))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>